#!/bin/bash
#
#SBATCH --array=1-4%1
#SBATCH --output=./jobfiles/group_runner%A-%a.out
#SBATCH --job-name=group_Am4
#SBATCH --time=70:00:00
#SBATCH -p serc
#SBATCH --verbose

echo "moving propper SST file into place"
rm -rf cp /scratch/users/mborrus/AM4/AM4_run_editable/INPUT/hadisst_sst.data.nc
cp /scratch/users/mborrus/AM4/extra_data/p4_SST.nc /scratch/users/mborrus/AM4/AM4_run_editable/INPUT/hadisst_sst.data.nc

echo "moving to AM4 runtime folder"
cd /scratch/users/mborrus/AM4/AM4_runtime_MB

echo "starting first run"
srun --partition=serc --constraint=CLASS:SH3_CBASE python am4_runner.py input_data_path=`cd ..;pwd`/AM4_run_editable work_dir=`cd ..;pwd`/SST_p4/${SLURM_ARRAY_TASK_ID} nml_template=input_xanadu_2021.01.nml n_cpu_atmos=96 runtime_months=3 runtime_days=10 modules=am4/singularity_gfdl/2021.1.0 hpc_config=sherlock3_base_singularity mpi_exec='srun' am4_container_pathname=${AM4_CONTAINER_PATHNAME} am4_exe=${AM4_GFDL_EXE} slurm_partition=serc slurm_time=23:00:00 do_batch=True
echo "first run submitted"

echo "moving propper SST file into place"
rm -rf cp /scratch/users/mborrus/AM4/AM4_run_editable/INPUT/hadisst_sst.data.nc
cp /scratch/users/mborrus/AM4/extra_data/m4_SST.nc /scratch/users/mborrus/AM4/AM4_run_editable/INPUT/hadisst_sst.data.nc

echo "starting second run"
srun --partition=serc --constraint=CLASS:SH3_CBASE python am4_runner.py input_data_path=`cd ..;pwd`/AM4_run_editable work_dir=`cd ..;pwd`/SST_m4/${SLURM_ARRAY_TASK_ID} nml_template=input_xanadu_2021.01.nml n_cpu_atmos=96 runtime_months=3 runtime_days=10 modules=am4/singularity_gfdl/2021.1.0 hpc_config=sherlock3_base_singularity mpi_exec='srun' am4_container_pathname=${AM4_CONTAINER_PATHNAME} am4_exe=${AM4_GFDL_EXE} slurm_partition=serc slurm_time=23:00:00 do_batch=True
echo "second run submitted"

echo "  entering hibernation"
sleep 12h
echo "awoke from hibernation"
#ml load netcdf

#cd $SCRATCH/AM4/co2/${SLURM_ARRAY_TASK_ID}
#mppnccombine -r 19790101.atmos_daily.tile1.nc
#mppnccombine -r 19790101.atmos_daily.tile2.nc
#mppnccombine -r 19790101.atmos_daily.tile3.nc
#mppnccombine -r 19790101.atmos_daily.tile4.nc
#mppnccombine -r 19790101.atmos_daily.tile5.nc
#mppnccombine -r 19790101.atmos_daily.tile6.nc

#cd $SCRATCH/AM4/quarter/${SLURM_ARRAY_TASK_ID}
#mppnccombine -r 19790101.atmos_daily.tile1.nc
#mppnccombine -r 19790101.atmos_daily.tile2.nc
#mppnccombine -r 19790101.atmos_daily.tile3.nc
#mppnccombine -r 19790101.atmos_daily.tile4.nc
#mppnccombine -r 19790101.atmos_daily.tile5.nc
#mppnccombine -r 19790101.atmos_daily.tile6.nc
